const categoriesList = [
  "Все фильмы",
  "Избранное",
  "Комедии",
  "Драмы",
  "Мелодрамы",
  "Триллеры",
  "Фэнтези",
  "Боевики",
  "История",
  "test",
  "test1",
  "test2",
  "test3",
  "test4",
  "test5",
  "test6",
  "test7",
];

const moviesList = [
  {
    id: "1",
    title: "Типа крутые легавые",
    category: ["Боевики", "Комедии"],
    year: 2007,
    country: ["Виликобритания", "Франция"],
    age: "16+",
    imdb: 7.8,
    kinopoisk: 7.6,
    poster: "src/image/movie/posters/hot-fuzz.webp"
  },
  {
    id: "2",
    title: "Монти Пайтон и священный Грааль",
    category: ["Комедии", "Фэнтези"],
    year: 1975,
    country: ["Виликобритания"],
    age: "12+",
    imdb: 8.2,
    kinopoisk: 7.8,
    poster: "src/image/movie/posters/monty.webp"
  },
  {
    id: "3",
    title: "Шазам!",
    category: ["Боевики", "Фэнтези"],
    year: 2019,
    country: ["Канада", "США"],
    age: "12+",
    imdb: 7.1,
    kinopoisk: 6.76,
    poster: "src/image/movie/posters/shazam.webp"
  },
  {
    id: "4",
    title: "Призрачная красота",
    category: ["Драмы", "Мелодрамы"],
    year: 2016,
    country: ["США"],
    age: "16+",
    imdb: 6.8,
    kinopoisk: 7.1,
    poster: "src/image/movie/posters/collateral.webp"
  },
  {
    id: "5",
    title: "Джонни Д.",
    category: ["Драмы", "История", "Боевик"],
    year: 2009,
    country: ["США", "Япония"],
    age: "16+",
    imdb: 7,
    kinopoisk: 7.1,
    poster: "src/image/movie/posters/public-enemies.webp"
  },
  {
    id: "6",
    title: "Дом странных детей Мисс Перегрин",
    category: ["Драмы", "Фэнтези"],
    year: 2019,
    country: ["США", "Великобритания"],
    age: "16+",
    imdb: 6.7,
    kinopoisk: 6.8,
    poster: "src/image/movie/posters/miss-peregrine.webp"
  },
  {
    id: "7",
    title: "Рождество на двоих",
    category: ["Мелодрамы", "Драмы", "Комедии"],
    year: 2019,
    country: ["Виликобритания", "США"],
    age: "16+",
    imdb: 6.5,
    kinopoisk: 6.8,
    poster: "src/image/movie/posters/last-christmas.webp"
  },
  {
    id: "8",
    title: "Аритмия",
    category: ["Драмы", "Мелодрамы"],
    year: 2017,
    country: ["Россия"],
    age: "18+",
    imdb: 7.4,
    kinopoisk: 7.7,
    poster: "src/image/movie/posters/arrhythmia.webp"
  },
  {
    id: "9",
    title: "Доктор Сон",
    category: ["Фэнтези", "Триллеры"],
    year: 2019,
    country: ["США"],
    age: "18+",
    imdb: 7.4,
    kinopoisk: 7.2,
    poster: "src/image/movie/posters/doctor-sleep.webp"
  },
  {
    id: "10",
    title: "Стекло",
    category: ["Триллеры"],
    year: 2019,
    country: ["США", "Китай"],
    age: "16+",
    imdb: 6.7,
    kinopoisk: 6.4,
    poster: "src/image/movie/posters/glass.webp"
  },
  {
    id: "11",
    title: "Превосходство",
    category: ["Драмы", "Триллеры"],
    year: 2014,
    country: ["Великобритания", "Китай"],
    age: "12+",
    imdb: 6.3,
    kinopoisk: 6.5,
    poster: "src/image/movie/posters/transcendence.webp"
  },
  {
    id: "12",
    title: "Агент Ева",
    category: ["Боевики", "Триллеры"],
    year: 2020,
    country: ["США"],
    age: "18+",
    imdb: 5.3,
    kinopoisk: 5.3,
    poster: "src/image/movie/posters/ava.webp"
  },
  {
    id: "13",
    title: "Дюнкерк",
    category: ["Драмы", "История"],
    year: 2017,
    country: ["Великобритания"],
    age: "16+",
    imdb: 7.9,
    kinopoisk: 7.3,
    poster: "src/image/movie/posters/dunkirk.webp"
  },
  {
    id: "14",
    title: "1917",
    category: ["Боевики", "История"],
    year: 2019,
    country: ["США"],
    age: "16+",
    imdb: 8.3,
    kinopoisk: 8.0,
    poster: "src/image/movie/posters/1917.webp"
  }
];
